In [1]:
import numpy as np
import pandas as pd
import matplotlib as mtb
import seaborn as sns

In [2]:
dress_details = pd.read_csv('D:\Data_Science\Project\data\\raw\Dress details.csv')
dress_sales = pd.read_csv('D:\Data_Science\Project\data\\raw\Dress sales.csv')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
C:\Users\RUSHANK\AppData\Local\Temp\ipykernel_6980\2796759666.py:1: SyntaxWarning: invalid escape sequence '\D'
  dress_details = pd.read_csv('D:\Data_Science\Project\data\\raw\Dress details.csv')
C:\Users\RUSHANK\AppData\Local\Temp\ipykernel_6980\2796759666.py:2: SyntaxWarning: invalid escape sequence '\D'
  dress_sales = pd.read_csv('D:\Data_Science\Project\data\\raw\Dress sales.csv')

In [3]:
dress_details.head(5)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,chiffonfabric,chiffon,bow,dot,0

In [4]:
dress_sales.head(5)

,Dress_ID,29-08-2013,31-08-2013,09-02-2013,09-04-2013,09-06-2013,09-08-2013,09-10-2013,09-12-2013,14-09-2013,...,24-09-2013,26-09-2013,28-09-2013,30-09-2013,10-02-2013,10-04-2013,10-06-2013,10-08-2013,10-10-2013,10-12-2013
0,1.006033e+09,2114,2274,2491,2660,2727,2887,2930,3119,3204,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
1,1.212192e+09,151,275,570,750,813,1066,1164,1558,1756,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
2,1.190381e+09,6,7,7,7,8,8,9,10,10,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
3,9.660060e+08,1005,1128,1326,1455,1507,1621,1637,1723,1746,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
4,8.763395e+08,996,1175,1304,1396,1432,1559,1570,1638,1655,...,2032,2156.0,2252,2312.0,2387.0,2459.0,2544,2614.0,2693.0,2736

In [5]:
dress_details['Size'] = dress_details.Size.replace({
    's' : 'Small',
    'S' : 'Small',
    'm' : 'Medium',
    'M' : 'Medium',
    'l' : 'Large',
    'L' : 'Large'
})

In [6]:
size_percentage = dress_details.Size.value_counts(normalize=True)*100

In [7]:
highest_percentage = size_percentage.max()
highest_percentage

np.float64(35.699373695198325)

In [8]:
lowest_percentage = size_percentage.get('Small',0)
lowest_percentage

np.float64(7.306889352818372)

In [9]:
dress_inclusive = pd.merge(dress_details,dress_sales, on='Dress_ID', how = 'inner')
dress_inclusive.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,Material,FabricType,...,24-09-2013,26-09-2013,28-09-2013,30-09-2013,10-02-2013,10-04-2013,10-06-2013,10-08-2013,10-10-2013,10-12-2013
0,1006032852,Sexy,Low,4.6,Medium,Summer,o-neck,sleevless,NaN,chiffon,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
1,1212192089,Casual,Low,0.0,Large,Summer,o-neck,Petal,microfiber,NaN,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
2,1190380701,vintage,High,0.0,Large,Automn,o-neck,full,polyster,NaN,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
3,966005983,Brief,Average,4.6,Large,Spring,o-neck,full,silk,chiffon,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
4,876339541,cute,Low,4.5,Medium,Summer,o-neck,butterfly,chiffonfabric,chiffon,...,2032,2156.0,2252,2312.0,2387.0,2459.0,2544,2614.0,2693.0,2736